### ISSUE TITLE
인터프리터 환경이란?

### ISSUE THREAD

**Issue by Jangdo** [Lutece/sundayJavascript#1]
교재 P.19 상단
<script> 요소 내부의 자바스크립트 코드는 위에서부터 차례로 해석됩니다.
이 예제에서는 먼저 함수 정의가 해석되어 **인터프리터 환경 내부**에 저장됩니다.

**Comment by Lutece** [comment]
@Jangdo  이 부분은 실행컨텍스트 내용이 도움이 될거같네요 :) '결국 코드의 실행순서에 따라 어떻게 어떻게 해석하는가' 라고도 볼 수 있는데 이건 참조값이 어떻게 쓰이는지, 컨텍스트가 무엇인지. 라는 내용부터 읽으면 해결되는 주제라고 생각됩니다.

**Comment by Jangdo** [comment]
네 감사합니다!!!
