### ISSUE TITLE
스트릭트 모드

### ISSUE THREAD

**Issue by Jangdo** [Lutece/sundayJavascript#2]
P.35 하단
"use strict"
이 선언은 마치 변수에 저장하지는 않는 문자열처럼 보이지만, 스트릭트 모드를 지원하는 자바스크립트 엔진은 이를 인식하고 스트릭트 모드로 전환합니다. 이 문법은 **ECMAScript 3 문법과 호환되도록 만든 것입니다.**

다음페이지에 스트릭트 모드를 지원하는 브라우저가 나오는데
익스10+, 파이어폭스4+...
그렇다면 익스10 미만 버전은 스트릭트 모드를 지원하지 않는지...?
또, ECMAScript 3 문법과 호환돼도록 만든 것이라는데...ECMAScript 3 는 이전 버전인데...앞뒤가...
이해가 잘 안됨.

**Comment by Lutece** [comment]
@Jangdo  use strict를 선언하게 되면 기존에 애매하게 처리되었던 부분들을 보다 엄격하게 판단하게 되고 에러를 발생시키게 되는 현상을 보실 수 있습니다. use strict를 선언하여 짜여진 코드가 use strict를 인식하지 못하는 하위 브라우저에서 돌아가지 않거나, 문제가 있는 경우는 거의 없는 것으로 알고 있습니다. 근데 use strict 선언여부에 대한 차이는 한번 자세히 찾아보고 정리하는 것도 좋을것같네요!

**Comment by Jangdo** [comment]
기존에 애매하게 처리되었던 부분 이라면 세미콜론을 제외하고 다른 부분은 어떤게 있을지 궁금하네요.

**Comment by Lutece** [comment]
넵 이번에 그런 부분들도 같이 조사해보는게 좋을거같습니다. 이번주에 그부분들도 각자 조사해오는게 좋지않을까요?

**Comment by Jangdo** [comment]
4장까지 먼저 읽고요....ㅜㅡㅜ 
close 할께요!
