### ISSUE TITLE
깊은복사에 대해 자세히 알아보기

### ISSUE THREAD

**Issue by Jangdo** [Lutece/sundayJavascript#6]
41p, 42p 
얕은 복사, 깊은복사의 예제가 하나씩 나오는데...

좀더 자세히 깊은복사에 대해 알아보기

예제

function copy( arr1, arr2 ){
    for(var i = 0; i < arr1.length; ++i){
        arr2[i] = arr1[i];
    }
}

var nums = [];
var samenums = [];
for(var i = 0; i < 10; ++i){
    nums[i] = i+1;
}

copy(nums, samenums);
nums[0] = 400;
console.log(samenums[0]);

**Comment by Lutece** [comment]
어떤 부분이 이해가 안가시는지 디테일하게 설명해주세요
